### PR TITLE
Add whenCmd

### PR DESCRIPTION
**Pull request by albertwoo**

### CODE REVIEW

**Comment by albertwoo** [comment]
@MangelMaxime what do you think about this PR?

**Comment by albertwoo** [comment]
https://github.com/slaveOftime/Fun.Build/issues/31

**Comment by MangelMaxime** [comment]
It looks good in to me in term of code usage.

Do you have an example of the generated help message?

**Comment by albertwoo** [comment]
If you write this:
```fsharp
pipeline "cmd-info" {
    description "Check cmd info build style"
    stage "" {
        whenAny {
            whenCmd {
                name "-w"
                alias "--watch"
                description "watch cool stuff"
            }
            whenCmd {
                name "run"
                description "run cool stuff"
                acceptValues [ "v1"; "v2" ]
            }
        }
        echo "here we are"
    }
    runIfOnlySpecified
}
```
You can get help info like:
```bash
Description:
  Pipeline cmd-info (command only help information)
  Check cmd info build style

Usage:
  dotnet fsi .\demo.fsx -- -p cmd-info [options]
  dotnet fsi .\demo.fsx -- -p cmd-info -h
  dotnet fsi .\demo.fsx -- -p cmd-info -h --verbose

Options(collected from stages):
  run  (v1, v2)                   run cool stuff
  -w, --watch                     watch cool stuff
  -h, --help                      Show help and usage information
  -v, --verbose                   Make the help information verbose
```

**Comment by MangelMaxime** [comment]
When reading, the help message I don't know how to read the `(...)`, I think I never saw parenthesis used in CLI documentation. 

Here is how `yargs` represents choices:

```
~/projects/node-sx4ggg 6s
❯ node index.js
Options:
      --version     Show version number                                [boolean]
  -i, --ingredient  choose your sandwich ingredients
                        [choices: "peanut-butter", "jelly", "banana", "pickles"]
      --help        Show help                                          [boolean]
```

I think this is what I am most used to read in other CLI tools too.

In your case it would gives:

```
Description:
  Pipeline cmd-info (command only help information)
  Check cmd info build style

Usage:
  dotnet fsi .\demo.fsx -- -p cmd-info [options]
  dotnet fsi .\demo.fsx -- -p cmd-info -h
  dotnet fsi .\demo.fsx -- -p cmd-info -h --verbose

Options(collected from stages):
  run                             run cool stuff
                                  [choices: "v1", "v2"]
  -w, --watch                     watch cool stuff
  -h, --help                      Show help and usage information
  -v, --verbose                   Make the help information verbose
```

Or perhaps:

```
  run  [choices: "v1", "v2"]                           run cool stuff
```

What do you think?

**Comment by albertwoo** [comment]
Changed it to:

```txt
  run                             run cool stuff
                                  [choices: "v1", "v2"]
```

**Comment by MangelMaxime** [comment]
Awesome thank you

**Pull request merged**
